FROM python:3
ENV PYTHONUNBUFFERED=1
RUN mkdir /app
WORKDIR /app
COPY django/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
RUN django-admin startproject user_mgmt
WORKDIR /app/user_mgmt
COPY django/settings.py user_mgmt/
COPY django/urls.py user_mgmt/
RUN mkdir /app/templates
COPY django/templates/ ./templates/
RUN python manage.py migrate
