version: '3.4'

services:
  server:
    restart: unless-stopped
    build:
      context: .
      target: datasette
    command:
      /usr/local/bin/datasette serve . --crossdb --root --load-extension=spatialite --setting default_page_size 25 --metadata config/metadata.yml -h 0.0.0.0 -p 8000
    ports:
      - 8000:8000
    environment:
      PYTHONUNBUFFERED: 1
      DEPLOY_GITHUB_TOKEN: ${DEPLOY_GITHUB_TOKEN}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    # we're not volumizing csvs/ because they're not available
    # during the build and we might want to bundle the data with
    # the docker container
    volumes:
      - .:/datasette
    networks:
      - dev

  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8001
    # TODO: remove later, use internal
    ports:
      - 8001:8001
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./secrets/sqlite3.db:/app/sqlite3.db
    networks:
      - dev

networks:
  dev:
    driver: bridge
